### ISSUE TITLE
Can you provide the values of the metric in the paper?

### ISSUE THREAD

**Issue by bbdamodaran** [YannickStruempler/inr_based_compression#1]
It would be great if you could provide the values of the metric (bpp and PSNR) used in the plots for atleast the kodak dataset.
it would be easier to compare.

thanks

**Comment by YannickStruempler** [comment]
Hi,
The main results of the paper (rate-distortion curves) are now available in the results folder.
I hope this is what you need.

**Comment by bbdamodaran** [comment]
yes, thanks
